Repository thoth-station/s2i-example, pull requests merged in 2022-11, with the labels that each got.

#34 :arrow_up: Keep the s2i-example up-to-date with ubi8-py3.8
  .thoth.yaml
  README.rst
  openshift.yaml
  requirements.txt
  thoth_conf_template.yaml
Labels: size/S

#35 Update to the full GVK
  openshift.yaml
Labels: size/XS, lgtm

#36 Updated to use the full GVK
  openshift.yaml
Labels: size/XS, lgtm

#37 Add prow configuration
  .aicoe-ci.yaml
  .pre-commit-config.yaml
  .prow.yaml
  .thoth.yaml
  OWNERS
Labels: size/M, lgtm

#38 :arrow_up: Keep the s2i-example hello-world up-to-date
  Pipfile
  Pipfile.lock
  openshift.yaml
  thoth_conf_template.yaml
Labels: size/S

#39 Set the information based on cowsay package
  Pipfile
  Pipfile.lock
  README.rst
  openshift.yaml
Labels: size/M
